// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.hamcrest.MatcherAssert.*;
import static org.hamcrest.CoreMatchers.*;
import static org.hamcrest.core.IsNot.not;
import static org.junit.Assert.assertTrue;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class InjectiontestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws MalformedURLException {
    driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), new ChromeOptions());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void injectiontest() {
    driver.get("http://127.0.0.1:8080/WebGoat/start.mvc#lesson/WebGoatIntroduction.lesson");
    {
      WebElement element = driver.findElement(By.linkText("(A1) Injection"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("(A1) Injection")).click();
    driver.findElement(By.id("A1Injection-SQLInjectionintro")).click();
    driver.findElement(By.cssSelector("a:nth-child(2) > .attack-link")).click();
    {
      WebElement element = driver.findElement(By.name("query"));
      Boolean isEditable = element.isEnabled() && element.getAttribute("readonly") == null;
      assertTrue(isEditable);
    }
    vars.put("sqlvar", "select department from employees where first_name=\'Bob\'");
   /* System.out.println("The sql statement is vars.get("sqlvar").toString()");*/
    driver.findElement(By.name("query ")).sendKeys(vars.get("sqlvar").toString());
    driver.findElement(By.name("query")).sendKeys(Keys.ENTER);
    vars.put("sqlresult", driver.findElement(By.cssSelector(".attack-feedback > .feedback-positive")).getText());
/*    System.out.println("Result = vars.get("sqlresult").toString()");*/
    driver.findElement(By.cssSelector("a:nth-child(9) > .attack-link")).click();
    {
      String value = driver.findElement(By.name("account")).getAttribute("value");
      assertThat(value, is("Smith"));
    }
    vars.put("default name", "name=account ");
    {
      String value = driver.findElement(By.name("operator ")).getAttribute("value");
      assertThat(value, is("or"));
    }
    vars.put("default operator", "name=operator");
    {
      String value = driver.findElement(By.name("injection")).getAttribute("value");
      assertThat(value, is("1 = 1"));
    }
    vars.put("default injection ", "name=injection");
    System.out.println("The defualt values are ${default name}, ${default operator} and ${default injection}");
    driver.findElement(By.name("Get Account Info")).click();
    vars.put("result", driver.findElement(By.xpath("//div[11]/div[2]/div[2]/span")).getText());
    if ((Boolean) js.executeScript("return (arguments[0] === \'No results matched. Try Again.\')", vars.get("result"))) {
      System.out.println("Wrong answer given ");
    }
    {
      WebElement dropdown = driver.findElement(By.name("account"));
      dropdown.findElement(By.xpath("//option[. = '\'']")).click();
    }
    {
      WebElement dropdown = driver.findElement(By.name("injection"));
      dropdown.findElement(By.xpath("//option[. = '\'1\' ']")).click();
    }
    driver.findElement(By.name("Get Account Info")).click();
  }
}
